### ISSUE TITLE
cant install

### ISSUE THREAD

**Issue by oleksandr-shvets** [burnnat/eslint-plugin-extjs#1]
Error: Definition for rule 'ext-deps' was not found.
Installed by `npm install --save-dev eslint-plugin-extjs`
Used eslint v0.22.1
my .eslintrc:

```
plugins: ["extjs"]

rules:
    ext-deps: [2, 2]
```

**Comment by burnnat** [comment]
As per the [ESLint documentation](http://eslint.org/docs/user-guide/configuring#configuring-plugins):

> To configure a rule which is defined within a plugin you have to prefix the rule ID with the plugin name and a `/`.

So your `.eslintrc` should look something like this:

```
{
    "plugins": ["extjs"],
    "rules": {
        "extjs/ext-deps": 2
    }
}
```

(The `ext-deps` rule doesn't take any additional arguments, so a simple `2` will work here.)

Also note this line from the documentation, if `eslint` is installed globally, then `eslint-plugin-extjs` will need to be installed globally as well:

> A globally-installed instance of ESLint can only use globally-installed ESLint plugins. A locally-installed ESLint can make sure of both locally- and globally- installed ESLint plugins.

**Comment by oleksandr-shvets** [comment]
Thank you for help!
But I'm still got error with ext-deps rule:
./node_modules/eslint-plugin-extjs/lib/rules/ext-deps.js:37
                calls[calls.length - 1].references[classes.alternates[typeName] || typeName]
                                       ^
TypeError: Cannot read property 'references' of undefined

ext-array-foreach and no-ext-create rules worked fine.

**Comment by burnnat** [comment]
Okay, that definitely looks like a bug. :smile:
Do you have a sample input that would produce this error?
