### ISSUE TITLE
Ext is not defined error

### ISSUE THREAD

**Issue by corywilliamson** [burnnat/eslint-plugin-extjs#4]
I have installed eslint-plugin-extjs locally, and configured it as:

```
"plugins": [
    "extjs"
  ]
```

There are no extra rules enabled. When I attempt to lint the code, I get this error for every file:
`error  "Ext" is not defined  no-undef`

Is there something simple I'm missing in order to use this plugin, or some additional configuration I need to add?

**Comment by corywilliamson** [comment]
I was able to get around it by adding

```
"globals": {
    "Ext": true
  }
```

Is bootstrap, or the Ext src assumed to be included in the lint process?

**Comment by burnnat** [comment]
You can configure ESLint to lint whatever files you want, but the [`no-undef`](http://eslint.org/docs/rules/no-undef) rule does not track what globals are defined across files, so including the ExtJS bootstrap or sources won't do anything about these warnings. Adding Ext in your globals configuration is the standard way of handling it.

**Comment by corywilliamson** [comment]
Ok. I assumed the plugin would have defined the global for me. All as well after adding it to globals.

**Comment by burnnat** [comment]
Yeah, I don't think there's a good way for plugins to specify globals like this, and I'm not aware of any other plugins that do. Glad you got it figured out :)
